services:
  gluetun-prowlarr:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges:true
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      # Proton credentials
      - WIREGUARD_PRIVATE_KEY=${HL_PROTON_WG_PRIVATE_KEY}
      # Free tier servers
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
      # Security
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
      # Common
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/gluetun-prowlarr:/gluetun
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - main

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/prowlarr:/config
    restart: unless-stopped
    depends_on:
      - gluetun-prowlarr
    network_mode: service:gluetun-prowlarr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - TZ=${HL_TZ}
    restart: unless-stopped
    networks:
      - main

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/sonarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - main

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/radarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - main

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/bazarr:/config
      - ${HL_DATA_FOLDER}/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - main

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.18-develop
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/readarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - main

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/lidarr:/config
      - ${HL_DATA_FOLDER}:/data
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - main

  questarr:
    image: ghcr.io/doezer/questarr:latest
    environment:
      - PUID=${HL_USER}
      - PGID=${HL_GROUP}
      - SQLITE_DB_PATH=/app/data/sqlite.db
    volumes:
      - ${HL_CONFIG_FOLDER}/questarr:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    external: true
