services:
  adguardhome:
    image: adguard/adguardhome:latest
    environment:
      - TZ=${HL_TZ}
    volumes:
      - ${HL_CONFIG_FOLDER}/adguardhome/work:/opt/adguardhome/work
      - ${HL_CONFIG_FOLDER}/adguardhome/conf:/opt/adguardhome/conf
    ports:
      # Servidor DNS "plain"
      - 53:53
      - 53:53/udp
      # Wizard inicial de AdGuard Home
      - 3000:3000
      # Panel de administración (HTTP)
      - 8083:8083
    restart: unless-stopped
    network_mode: host
